[project]
name = "apantias"
version = "2.0.4"
authors = [
    { name="Florian Heinrich", email="florianheinrich@gmx.at" },
]
description = "Tools for analysis of data from the DANAE experiment on HEPHY"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dask>=2026.3.0",
    "distributed>=2026.3.0",
    "h5py>=3.16.0",
    "pyyaml>=6.0.3",
    "zarr>=3.1.6",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
    "pylint>=4.0.5",
    "ruff>=0.15.2",
]

[project.urls]
Homepage = "https://github.com/shakamaran/apantias"
Issues = "https://github.com/shakamaran/apantias/issues"

[tool.pylint]
disable = [
    "R0903",
    "R0914",
    "C0301",
    "W0105",
    "E1133",
    "E1101",
]
